### ISSUE TITLE
testing mentions inside code

### ISSUE THREAD

**Issue by leopoldomt** [shaker-project/shaker#1]
this is just to test whether adding a mention to a user inside code will result in an email sent to said user. 

`@damorim`
`@denini08`
`@shaker-project`
`@leopoldomt`

**Comment by shaker-project** [comment]
* [aaa](https://github.com/STAR-RG/shaker/blob/master/test/exec.py#L30)

**Comment by leopoldomt** [comment]
[teste](https://github.com/STAR-RG/shaker/blob/master/test/exec.py#L102-L108)
